### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [dabachma/promaides_gis_tools#1]
# problem

Can you please fix the metadata links for the uploaded plugin. 
The issue tracker link does not point to the correct link.
The plugin homepage doesn't point to a page with any description. Rather use the same link for the repo if you do not have a dedicated link.

After fixing these update the plugin in the repo

**Comment by dabachma** [comment]
Dear Sir or Madame,
thanks for the infos; changed the links in the meta-data.
Regards
Daniel Bachmann
